### ISSUE TITLE
test fails with ruby 2.4

### ISSUE THREAD

**Issue by mtasaka** [ClusterLabs/pcs#126]
We are now rebuilding packages against ruby 2.4 and now pcs (pcs-0.9.155-1.fc26) fails on test suite as: https://koji.fedoraproject.org/koji/taskinfo?taskID=17263481
```
+ GEM_HOME=/builddir/build/BUILDROOT/pcs-0.9.155-1.fc26.i386/usr/lib/pcsd/vendor/bundle/ruby
+ ruby -I/builddir/build/BUILDROOT/pcs-0.9.155-1.fc26.i386/usr/lib/pcsd -I/builddir/build/BUILDROOT/pcs-0.9.155-1.fc26.i386/usr/lib/pcsd/test /builddir/build/BUILDROOT/pcs-0.9.155-1.fc26.i386/usr/lib/pcsd/test/test_all_suite.rb
/usr/share/gems/gems/backports-3.6.4/lib/backports/1.8.7/fixnum/div.rb:1: warning: constant ::Fixnum is deprecated
/usr/share/gems/gems/backports-3.6.4/lib/backports/1.8.7/fixnum/fdiv.rb:1: warning: constant ::Fixnum is deprecated
/usr/share/gems/gems/backports-3.6.4/lib/backports/2.1.0/bignum/bit_length.rb:1: warning: constant ::Bignum is deprecated
/usr/share/gems/gems/backports-3.6.4/lib/backports/2.1.0/fixnum/bit_length.rb:1: warning: constant ::Fixnum is deprecated
Loaded suite /builddir/build/BUILDROOT/pcs-0.9.155-1.fc26.i386/usr/lib/pcsd/test/test_all_suite
Started
..............................F
===============================================================================
Failure: test_parse_malformed(TestConfig)
/builddir/build/BUILDROOT/pcs-0.9.155-1.fc26.i386/usr/lib/pcsd/test/test_config.rb:125:in `test_parse_malformed'
     122:   ]
     123: }'
     124:     cfg = PCSConfig.new(text)
  => 125:     assert_equal(
     126:       [[
     127:         'error',
     128:         "Unable to parse pcs_settings file: 399: unexpected token at '\"rh71-node2\"\n      ]\n    }\n  ]\n}'"
<[["error",
  "Unable to parse pcs_settings file: 399: unexpected token at '\"rh71-node2\"\n" +
  "      ]\n" +
  "    }\n" +
  "  ]\n" +
  "}'"]]> expected but was
<[["error",
  "Unable to parse pcs_settings file: 409: unexpected token at '\"rh71-node2\"\n" +
  "      ]\n" +
  "    }\n" +
  "  ]\n" +
  "}'"]]>
diff:
  [["error",
?   "Unable to parse pcs_settings file: 399: unexpected token at '\"rh71-node2\"\n" +
?                                       40                                           
    "      ]\n" +
    "    }\n" +
    "  ]\n" +
    "}'"]]
===============================================================================
...............................................................................
..............................
Finished in 19.131468935 seconds.
------
140 tests, 1536 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
99.2857% passed
------
7.32 tests/s, 80.29 assertions/s
```

I guess this is because (rubygem-)json was updated from 1.8.2 to 2.0.2 and error format changed somehow, however I have not investigated this further.

**Comment by voxik** [comment]
Yep, seems to be due to JSON:

```
$ gem list

*** LOCAL GEMS ***

json (2.0.3, 1.8.3)
power_assert (0.4.1)
psych (2.1.0)
rdoc (4.2.2)
test-unit (3.2.3)
```

```
$ irb
irb(main):001:0> RUBY_VERSION
=> "2.3.3"
irb(main):002:0> require 'json'
=> true
irb(main):003:0> JSON::VERSION
=> "1.8.3"
irb(main):004:0>     text =
irb(main):005:0* '{
irb(main):006:0'   "data_version": 9,
irb(main):007:0'   "clusters": [
irb(main):008:0'     {
irb(main):009:0'       "name": "cluster71",
irb(main):010:0'       "nodes": [
irb(main):011:0'         "rh71-node1"
irb(main):012:0'         "rh71-node2"
irb(main):013:0'       ]
irb(main):014:0'     }
irb(main):015:0'   ]
irb(main):016:0' }'
=> "{\n  \"data_version\": 9,\n  \"clusters\": [\n    {\n      \"name\": \"cluster71\",\n      \"nodes\": [\n        \"rh71-node1\"\n        \"rh71-node2\"\n      ]\n    }\n  ]\n}"
irb(main):017:0> JSON.parse text
JSON::ParserError: 399: unexpected token at '"rh71-node2"
      ]
    }
  ]
}'
	from /usr/share/ruby/json/common.rb:155:in `parse'
	from /usr/share/ruby/json/common.rb:155:in `parse'
	from (irb):17
	from /usr/bin/irb:11:in `<main>'
irb(main):018:0> 
```

```
$ irb
irb(main):001:0> RUBY_VERSION
=> "2.3.3"
irb(main):002:0> gem 'json'
=> true
irb(main):003:0> require 'json'
=> true
irb(main):004:0> JSON::VERSION
=> "2.0.3"
irb(main):005:0>     text =
irb(main):006:0* '{
irb(main):007:0'   "data_version": 9,
irb(main):008:0'   "clusters": [
irb(main):009:0'     {
irb(main):010:0'       "name": "cluster71",
irb(main):011:0'       "nodes": [
irb(main):012:0'         "rh71-node1"
irb(main):013:0'         "rh71-node2"
irb(main):014:0'       ]
irb(main):015:0'     }
irb(main):016:0'   ]
irb(main):017:0' }'
=> "{\n  \"data_version\": 9,\n  \"clusters\": [\n    {\n      \"name\": \"cluster71\",\n      \"nodes\": [\n        \"rh71-node1\"\n        \"rh71-node2\"\n      ]\n    }\n  ]\n}"
irb(main):018:0> JSON.parse text
JSON::ParserError: 409: unexpected token at '"rh71-node2"
      ]
    }
  ]
}'
	from /builddir/.gem/ruby/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
	from /builddir/.gem/ruby/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
	from (irb):18
	from /usr/bin/irb:11:in `<main>'
```

**Comment by voxik** [comment]
The numbers refer to the line of code of the Ragel parser if I am not mistaken, so they are implementation detail and should not be part of the test case IMO.

**Comment by tomjelinek** [comment]
Fixed in https://github.com/ClusterLabs/pcs/commit/b585106150721d0a50504a9c762478ec9dd18778. Thanks for reporting the issue.
