### ISSUE TITLE
pcsd fails to start under systemd: can't modify frozen String (RuntimeError)

### ISSUE THREAD

**Issue by elpetak** [ClusterLabs/pcs#134]
Running version 0.9.152 of pcs (redhat package pcs-0.9.152-10.el7.x86_64)
when starting pcsd from systemd I get:
```
/usr/lib/pcsd/ssl.rb:83:in `[]=': can't modify frozen String (RuntimeError)
	from /usr/lib/pcsd/ssl.rb:83:in `block in run_server'
	from /usr/lib/pcsd/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/handler/webrick.rb:33:in `run'
	from /usr/lib/pcsd/ssl.rb:69:in `run_server'
	from /usr/lib/pcsd/ssl.rb:160:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/pcsd/pcsd:14:in `<main>'
```

**Comment by tomjelinek** [comment]
Thank you for reporting and fixing this issue.
