### ISSUE TITLE
run pcs on fedora27 with error

### ISSUE THREAD

**Issue by liu4480** [ClusterLabs/pcs#157]
#pcs --help
Traceback (most recent call last):
  File "/usr/sbin/pcs", line 11, in <module>
    load_entry_point('pcs==0.9.160', 'console_scripts', 'pcs')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/pcs/app.py", line 12, in <module>
    from pcs import (
  File "/usr/lib/python3.6/site-packages/pcs/acl.py", line 9, in <module>
    from pcs import (
  File "/usr/lib/python3.6/site-packages/pcs/prop.py", line 10, in <module>
    from pcs import (
  File "/usr/lib/python3.6/site-packages/pcs/node.py", line 10, in <module>
    from pcs import (
  File "/usr/lib/python3.6/site-packages/pcs/utils.py", line 27, in <module>
    from pcs.common import (
  File "/usr/lib/python3.6/site-packages/pcs/common/pcs_pycurl.py", line 8, in <module>
    from pycurl import *
ImportError: /usr/lib64/python3.6/site-packages/pycurl.cpython-36m-x86_64-linux-gnu.so: file too short

#rpm -qa|grep pcs
pcsc-lite-1.8.22-3.fc27.x86_64
pcs-0.9.160-1.fc27.x86_64
pcsc-lite-libs-1.8.22-3.fc27.x86_64
pcsc-lite-ccid-1.4.27-3.fc27.x86_64

**Comment by tomjelinek** [comment]
I am unable to reproduce this.

Based on the error message you provided it looks like the issue is not in pcs. I think the file `/usr/lib64/python3.6/site-packages/pycurl.cpython-36m-x86_64-linux-gnu.so` is somehow broken on your machine. Try reinstalling the `python3-pycurl` package.

**Comment by liu4480** [comment]
@tomjelinek , thanks, I just reinstalled, still could not work. but after I copied the file from other systems, it works. I know it is not a pcs issue, feel free to close
