### ISSUE TITLE
Can't authorize nodes with pcs auth

### ISSUE THREAD

**Issue by aqibsg** [ClusterLabs/pcs#188]
While running the pcs auth command, it breaks without even giving the username and password and gives the following error:

`sudo pcs auth`

> Traceback (most recent call last):
  File "/usr/sbin/pcs", line 9, in <module>
    load_entry_point('pcs==0.10.1', 'console_scripts', 'pcs')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pcs/app.py", line 6, in <module>
    from pcs import (
  File "/usr/lib/python3/dist-packages/pcs/acl.py", line 3, in <module>
    from pcs import (
  File "/usr/lib/python3/dist-packages/pcs/prop.py", line 4, in <module>
    from pcs import (
  File "/usr/lib/python3/dist-packages/pcs/utils.py", line 894
    f"{node}: Username and/or password is incorrect",
                                                   ^
SyntaxError: invalid syntax

**Comment by ondrejmular** [comment]
Which python version are you using?
pcs since version 0.10 requires python 3.6 or higher. For older python use pcs 0.9.x from pcs-0.9 branch as described in [README.md](https://github.com/ClusterLabs/pcs/blob/master/README.md)

**Comment by aqibsg** [comment]
after updating it to 3.6.1, it gave me another error 
**Error: Unexpected response from <ip>**

**Comment by tomjelinek** [comment]
`pcs auth` is not an existing pcs command. Can you run the command which fails for you with `--debug` and post both the command and its output? You may want to obscure passwords in the output before posting it.

**Comment by tomjelinek** [comment]
Closing for inactivity.
If you are still experiencing the issue and are willing to provide more info as has been requested, feel free to reopen.
