### ISSUE TITLE
when I run pcs on linux with an error of python

### ISSUE THREAD

**Issue by GitSoftwareNow** [ClusterLabs/pcs#202]
pcs status
Traceback (most recent call last):
  File "/usr/sbin/pcs", line 9, in <module>
    load_entry_point('pcs==0.9.165', 'console_scripts', 'pcs')()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 348, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2311, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2025, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python3.4/site-packages/pcs/app.py", line 12, in <module>
    from pcs import (
  File "/usr/lib/python3.4/site-packages/pcs/cluster.py", line 1141
    except KeyError, ValueError:
                   ^
SyntaxError: invalid syntax

**Comment by idevat** [comment]
This has been fixed in pcs-0.9.166 by 102e1d2.
