### ISSUE TITLE
pcs stonith sbd disable TypeError

### ISSUE THREAD

**Issue by Thermi** [ClusterLabs/pcs#208]
Hi,

When I run `pcs stonith sbd disable` on Arch with pcs 0.10.2, it fails. Please fix.

Kind regards

Thermi

Traceback:

```
[root@storage ~]# pcs stonith sbd disable
Traceback (most recent call last):
  File "/usr/bin/pcs", line 11, in <module>
    load_entry_point('pcs==0.10.2', 'console_scripts', 'pcs')()
  File "/usr/lib/python3.7/site-packages/pcs/app.py", line 232, in main
    utils.get_library_wrapper(), argv, utils.get_input_modifiers()
  File "/usr/lib/python3.7/site-packages/pcs/cli/common/routing.py", line 17, in _router
    return cmd_map[sub_cmd](lib, argv_next, modifiers)
  File "/usr/lib/python3.7/site-packages/pcs/cli/common/routing.py", line 17, in _router
    return cmd_map[sub_cmd](lib, argv_next, modifiers)
  File "/usr/lib/python3.7/site-packages/pcs/cli/common/routing.py", line 17, in _router
    return cmd_map[sub_cmd](lib, argv_next, modifiers)
  File "/usr/lib/python3.7/site-packages/pcs/stonith.py", line 610, in sbd_disable
    lib.sbd.disable_sbd(modifiers.get("--skip-offline"))
  File "/usr/lib/python3.7/site-packages/pcs/cli/common/lib_wrapper.py", line 86, in decorated_run
    return run_with_middleware(run, cli_env, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pcs/cli/common/middleware.py", line 13, in run
    return next_in_line(env, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pcs/cli/common/lib_wrapper.py", line 76, in run
    lib_call_result = run_library_command(lib_env, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pcs/lib/commands/sbd.py", line 272, in disable_sbd
    lib_env.get_node_target_factory().get_target_list(
  File "/usr/lib/python3.7/site-packages/pcs/lib/env.py", line 389, in get_node_target_factory
    self.__get_known_hosts(), self.report_processor
  File "/usr/lib/python3.7/site-packages/pcs/lib/env.py", line 403, in __get_known_hosts
    self._known_hosts = self._known_hosts_getter()
  File "/usr/lib/python3.7/site-packages/pcs/utils.py", line 280, in read_known_hosts_file
    output, retval = run_pcsdcli("read_known_hosts")
  File "/usr/lib/python3.7/site-packages/pcs/utils.py", line 842, in run_pcsdcli
    gem_home = os.path.join(pcsd_dir_path, settings.pcsd_gem_path)
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by tomjelinek** [comment]
Hi,

I believe I fixed this issue in https://github.com/ClusterLabs/pcs/commit/230cb99ad69ee3ad2a970f103e448f67ff813055. Let me know if the fix does not work for you.

**Comment by Thermi** [comment]
Works.

**Comment by tomjelinek** [comment]
Thank you for reporting the issue and testing the fix.
