### ISSUE TITLE
I cant start cluster  erreur  pcs 0.9 // python2.7

### ISSUE THREAD

**Issue by voipsense** [ClusterLabs/pcs#217]
Dear , 
pcs                                      x86_64                                      0.9.167-3.el7.centos.1
corosync                                                x86_64                                  2.4.3-6.el7_7.1                                     
 corosynclib                                             x86_64                                  2.4.3-6.el7_7.1                                     
 pacemaker                                               x86_64                                  1.1.20-5.el7_7.1                                    
 pacemaker-cli                                           x86_64                                  1.1.20-5.el7_7.1                                    
 pacemaker-cluster-libs                                  x86_64                                  1.1.20-5.el7_7.1                                    
 pacemaker-libs                                          x86_64                                  1.1.20-5.el7_7.1          
python2.7
   
I get this erreur when start cluster

[root@node1 /]# pcs cluster start –all
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/pcs/cluster.py", line 1140, in run
    code, output = utils.getPcsdCapabilities(self.node)
  File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 182, in getPcsdCapabilities
    node, 'remote/capabilities', printResult=False, printSuccess=False
  File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 508, in sendHTTPReq
    handler.setopt(pycurl.URL, url.encode("utf-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8: ordinal

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 1273, in worker
    returncode, output = action(node, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 313, in startPacema
    node, quiet=quiet, timeout=timeout, pacemaker=True, corosync=False
  File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 336, in startCluste
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 508, in sendHTTPReq
    handler.setopt(pycurl.URL, url.encode("utf-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8: ordinal

**Comment by voipsense** [comment]
Resolve err in syntax
# pcs cluster start --all  ==> ok

to debug :../pcs /utils.py

import sys
# encoding=utf8
reload(sys)
sys.setdefaultencoding('utf8')
