### ISSUE TITLE
UnboundLocalError: cannot access local variable 'lib' where it is not associated with a value

### ISSUE THREAD

**Issue by sergey-safarov** [ClusterLabs/pcs#592]
When I execute `pcs resource restart some_resource` I see error
```
[root@wc-0 ~]# pcs resource restart frr
Traceback (most recent call last):
  File "/usr/sbin/pcs", line 33, in <module>
    sys.exit(load_entry_point('pcs==0.11.3', 'console_scripts', 'pcs')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pcs/app.py", line 273, in main
    routing.create_router(cmd_map, [])(
  File "/usr/lib/python3.11/site-packages/pcs/cli/common/routing.py", line 33, in _router
    return cmd_map[sub_cmd](lib, argv_next, modifiers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pcs/cli/common/routing.py", line 33, in _router
    return cmd_map[sub_cmd](lib, argv_next, modifiers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pcs/resource.py", line 2603, in resource_restart
    _check_is_not_stonith(lib, [argv[0]])
                          ^^^
UnboundLocalError: cannot access local variable 'lib' where it is not associated with a value
```

Here
```
[root@wc-0 ~]# cat /etc/os-release 
NAME="Fedora Linux"
VERSION="37.20221106.1.0 (CoreOS)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora CoreOS 37.20221106.1.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='37.20221106.1.0'
```
and
```
[root@wc-0 ~]# rpm -qf /usr/sbin/pcs
pcs-0.11.3-4.fc37.aarch64
```

**Comment by tomjelinek** [comment]
Hi @sergey-safarov,

Thank you for taking time to report this issue. The bug has been already fixed upstream: https://github.com/ClusterLabs/pcs/commit/08a62b6e84db56cc3871c81826a420e22f726a65. Updated Fedora packages will be available within few weeks.
