### ISSUE TITLE
pcs resource move on debian 12 (bookworm) failed

### ISSUE THREAD

**Issue by gaevzynia** [ClusterLabs/pcs#696]
> pcs --version
> 0.11.5
> corosync -v
> Corosync Cluster Engine, version '3.1.7'
> pacemakerd -$
> Pacemaker 2.1.5
> uname -a
> Linux zbproxy1 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

When I am trying to move resource by pcs the action is  failed
_pcs resource move ZabbixProxy_
```
Traceback (most recent call last):
  File "/usr/sbin/pcs", line 33, in <module>
    sys.exit(load_entry_point('pcs==0.11.5', 'console_scripts', 'pcs')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/app.py", line 273, in main
    routing.create_router(cmd_map, [])(
  File "/usr/lib/python3/dist-packages/pcs/cli/common/routing.py", line 33, in _router
    return cmd_map[sub_cmd](lib, argv_next, modifiers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/cli/common/routing.py", line 33, in _router
    return cmd_map[sub_cmd](lib, argv_next, modifiers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/resource.py", line 854, in resource_move
    lib.resource.move_autoclean(
  File "/usr/lib/python3/dist-packages/pcs/cli/common/lib_wrapper.py", line 95, in decorated_run
    return run_with_middleware(run, cli_env, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/cli/common/middleware.py", line 14, in run
    return next_in_line(env, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/cli/common/middleware.py", line 42, in apply
    result_of_next = next_in_line(env, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/cli/common/middleware.py", line 80, in apply
    result_of_next = next_in_line(env, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/cli/common/lib_wrapper.py", line 86, in run
    lib_call_result = run_library_command(lib_env, *args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/lib/commands/resource.py", line 1823, in move_autoclean
    _, move_transitions, after_move_simulated_cib = simulate_cib(
                                                    ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/lib/pacemaker/live.py", line 426, in simulate_cib
    plaintext_result, transitions_xml, new_cib_xml = simulate_cib_xml(
                                                     ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pcs/lib/pacemaker/live.py", line 387, in simulate_cib_xml
    with tools.get_tmp_file() as new_cib_file, tools.get_tmp_file() as transitions_file:
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 289, in helper
    return _GeneratorContextManager(func, args, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 105, in __init__
    self.gen = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
TypeError: get_tmp_file() missing 1 required positional argument: 'data'
```

 _pcs status_
```
Cluster name: zbproxycluster
Status of pacemakerd: 'Pacemaker is running' (last updated 2023-06-15 08:57:04 +03:00)
Cluster Summary:
  * Stack: corosync
  * Current DC: zbproxy1 (version 2.1.5-a3f44794f94) - partition with quorum
  * Last updated: Thu Jun 15 08:57:04 2023
  * Last change:  Wed Jun 14 17:13:32 2023 by root via crm_resource on zbproxy2
  * 3 nodes configured
  * 5 resource instances configured

Node List:
  * Online: [ zbproxy1 zbproxy2 zbproxy3 ]

Full List of Resources:
  * Resource Group: zabbixGroup:
    * ClusterIP (ocf:heartbeat:IPaddr2):         Started zbproxy1
    * ZabbixProxy       (systemd:zabbix-proxy):  Started zbproxy1
  * fence_zbproxy1      (stonith:fence_vmware_rest):     Started zbproxy3
  * fence_zbproxy2      (stonith:fence_vmware_rest):     Started zbproxy3
  * fence_zbproxy3      (stonith:fence_vmware_rest):     Started zbproxy2

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
```

**Comment by tomjelinek** [comment]
Hi  @gaevzynia,

Thank you for reporting this issue. This regression has been fixed already in 2ab9e9c4fd1f26e5320c7585a83ba5d1857d4042. New pcs version containing the fix will be released in upstream shortly. We are sorry for any related inconvenience.
